//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_API.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNTS_BALANCE_RESUME
    {
        public string ID_CUENTA { get; set; }
        public string DESCRIPCION_CUENTA { get; set; }
        public string NATURALEZA { get; set; }
        public string DESCRIPCION_CATEGORIA { get; set; }
        public Nullable<double> TOTAL_DEBITOS { get; set; }
        public Nullable<double> TOTAL_CREDITOS { get; set; }
        public Nullable<double> BALANCE { get; set; }
    }
}
