//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_API.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA_ERRORES
    {
        public int ID_ERROR { get; set; }
        public string PANTALLA { get; set; }
        public string ERROR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
