//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_API.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASE_CUENTA
    {
        public int ID_CLASE_CUENTA { get; set; }
        public int ID_CLASE { get; set; }
        public string ID_CUENTA { get; set; }
        public int ID_CATEGORIA_CUENTA { get; set; }
    
        public virtual CATEGORIA_CUENTA CATEGORIA_CUENTA { get; set; }
        public virtual CLASE CLASE { get; set; }
        public virtual CUENTA_CONTABLE CUENTA_CONTABLE { get; set; }
    }
}
