//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_API.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASSES_LIST
    {
        public int ID_CLASE { get; set; }
        public string DESCRIPCION_CLASE { get; set; }
        public string CUENTA_ACTIVO { get; set; }
        public string CUENTA_GASTO { get; set; }
        public string CUENTA_DEP_ACUMULADA { get; set; }
        public Nullable<int> VIDA_UTIL { get; set; }
    }
}
