//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_API.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESUMEN_ASIENTOS
    {
        public int ID_ASIENTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DESCRIPCION { get; set; }
        public string DESCRIPCION_CLASE { get; set; }
        public Nullable<double> TOTAL_ASIENTO { get; set; }
    }
}
