//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_API.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESUMEN_VALIDACIONES_COMPLETAS
    {
        public Nullable<int> ID_ACTIVO { get; set; }
        public Nullable<int> ID_CLASE { get; set; }
        public string DESCRIPCION_ACTIVO { get; set; }
        public int ID_TIPO_VALIDACION { get; set; }
        public string DESCRIPCION_VALIDACION { get; set; }
        public string VALOR { get; set; }
    }
}
